using System.Web;
using System.Web.Mvc;
using $safeprojectname$.Filters;

namespace $safeprojectname$.Helpers
{
    /// <summary>
    /// Provides helpers for writing the CSP nonce into Razor output.
    /// </summary>
    public static class NonceHelper
{
    #region Provides helpers for writing the CSP nonce into Razor output.

    /// <summary>
    /// Gets the request-level CSP nonce generated by <see cref="ContentSecurityPolicyFilter"/>.
    /// </summary>
    /// <param name="helper">The Razor HTML helper instance.</param>
    /// <returns>The request nonce wrapped as <see cref="IHtmlString"/>.</returns>
    public static IHtmlString CspNonce(this HtmlHelper helper)
    {
        var nonce = helper.ViewContext.HttpContext.Items[ContentSecurityPolicyFilter.NonceKey] as string;

        return new HtmlString(nonce);
    }
    #endregion
}
}

